### ISSUE TITLE
Small patch to support FreeBSD cron job file group attribute

### ISSUE THREAD

**Issue by sch-it** [voxpupuli/puppet-cron#108]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.11
- Ruby: 2.7.5
- Distribution:  FreeBSD 13
- Module version:  2.0.0

## How to reproduce (e.g Puppet code you use)
  class { 'cron':
    manage_package => false,
  }
  cron::job { 'test_resource':
    command => '/usr/sbin/sleep 1',
    user    => 'sch',
    hour    => 2,
    minute  => 0,
  }

## What are you seeing
Error: Could not set 'file' on ensure: Could not find group root (file: /etc/puppetlabs/code/environments/production/modules/cron/manifests/job.pp, line: 70)
Wrapped exception:
Could not find group root
Error: /Stage[main]/Main/Node[storage2.domain.com]/Cron::Job[test_resource]/File[job_test_resource]/ensure: change from 'absent' to 'file' failed: Could not set 'file' on ensure: Could not find group root (file: /etc/puppetlabs/code
/environments/production/modules/cron/manifests/job.pp, line: 70)

## Any additional information you'd like to impart
The 'file' resource declared in job.pp uses the fixed value 'root' for the 'group' parameter, but FreeBSD system uses the group 'wheel' and there is no group 'root'.
A possible solution is to define a group based on the $::osfamily fact.
The manifest job.pp might be modifed as follows

```
--- job_linux.pp        2022-06-28 09:35:31.984345992 +0000
+++ job.pp      2022-06-28 09:21:08.241957487 +0000
@@ -59,6 +59,15 @@

   assert_type(Cron::Jobname, $title)

+  case $::osfamily {
+    'FreeBSD': {
+      $groupname = 'wheel'
+    }
+    default: {
+      $groupname = 'root'
+    }
+  }
+
   case $ensure {
     'absent':  {
       file { "job_${title}":
@@ -70,7 +79,7 @@
       file { "job_${title}":
         ensure  => 'file',
         owner   => 'root',
-        group   => 'root',
+        group   => $groupname,
         mode    => $mode,
         path    => "/etc/cron.d/${title}",
         content => template('cron/job.erb'),
```

**Comment by smortex** [comment]
Do you mind opening a PR that fix it?  Thanks!

**Comment by sch-it** [comment]
I have checked the version 3.0 of the module, there is fixed code in the job.pp, so this issue is not relevant anymore

**Comment by smortex** [comment]
Ah :-)  Feel free to submit PRs if you find another issue!
