### ISSUE TITLE
Support for /var/spool/cron 

### ISSUE THREAD

**Issue by bschonec** [voxpupuli/puppet-cron#132]
While systemd timers are the preferred method on modern Linux OSes and /etc/cron.d is a supported method, some application vendors still require that users have their own cron jobs in /var/spool/cron/<user>.

I have an application that creates an application user that has to manage its own cron jobs.  Since all files in /etc/cron.d are owned by root, the non-root users cannot manage their own cron jobs.

[puppetlabs-cron_core](https://github.com/puppetlabs/puppetlabs-cron_core/tree/main) cannot co-exist with puppet-cron so using puppetlabs-cron_core one loses the ability to manage /etc/cron.allow.

Wouldn't it be fairly trivial to support the old style /var/spool/cron/<user> methodology?

**Comment by yakatz** [comment]
What do you mean by support? If the cron job is managed by puppet, the application user won't get able to modify it because puppet will change it back.

**Comment by bschonec** [comment]
You're correct.  /var/spool/cron/<user> support would still be nice.

**Comment by yakatz** [comment]
To be clear, are you are saying you want this module to also duplicate the functionality of the core module and give you the option of which method to use for a job?

**Comment by yakatz** [comment]
The user story makes it clear, thanks. I am trying to pull some attention to this on Slack/libera so we can decide what to do.

**Comment by bschonec** [comment]
I'm working on a very rough draft of my ideas in a pull request.  The only gotcha I see so far is:

```
if $default_cron_job_path != /etc/cron.d {
  $path = "${cronjob_path}/${user}/$job_name"
| else {
  $path = "/etc/cron.d/${title}"
}

```

**Comment by yakatz** [comment]
I don't know that /var/spool/cron supports directories - usually there is just a file there.

**Comment by bschonec** [comment]
> I don't know that /var/spool/cron supports directories - usually there is just a file there.

Whoop...my mistake.  /var/spool/cron/<user> is the intended $path.

**Comment by ekohl** [comment]
> [puppetlabs-cron_core](https://github.com/puppetlabs/puppetlabs-cron_core/tree/main) cannot co-exist with puppet-cron so using puppetlabs-cron_core one loses the ability to manage /etc/cron.allow.

I thought cron_core is always present in puppet-agent. I don't see the conflict. You can even deploy it your environment as `cron_core` without issue.

**Comment by bschonec** [comment]
My apologies. I did manage to figure out using cron_core and puppet-cron.
