### ISSUE TITLE
Code in init.pp doesn't match defined types

### ISSUE THREAD

**Issue by MartinPetkov** [voxpupuli/puppet-cron#31]
In init.pp, there are lookups and instantiations for each cron interval defined type, but they don't match the actual defined types for hourly, daily, weekly and monthly.

I.e. in init.pp you have "cron::job::hourly" but the actual type is "cron::hourly".

**Comment by parkr** [comment]
Fixed by 61515cf5a9ef67e0cba531f2af3ad09b04101295

**Comment by juniorsysadmin** [comment]
Fixed by #40
