### ISSUE TITLE
Comma character in hour/minute parameters

### ISSUE THREAD

**Issue by repperille** [voxpupuli/puppet-cron#49]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 2018.1.0
- Module version: puppet-cron 1.2.0

## How to reproduce (e.g Puppet code you use)

If you have an hour or minute expression with comma like 0,5,10,15 you get a type failure because the Cron::Hour and Cron::Minute types does not allow comma in the expression. It is a valid cron expression though.

For example:
Every hour at minutes 15, 30 and 45 (15,30,45 * ? * *)

cron::job { 'myjob':
  minute      => '15,30,45',
  hour        => '*',
  date        => '*',
  month       => '*',
  weekday     => '*',
  user        => 'root',
  command     => 'my-command,
  environment => [ 'MAILTO=root', 'PATH="/usr/bin:/bin"', ],
}

Would it break the intension of the type pattern matching to allow comma?

Valid $minute parameter to Cron::Job.
type Cron::Minute = Variant[
  Integer[0,59],
  Pattern[/\A(([0-9]|[1-5][0-9])|(\*|(([0-9]|[1-5][0-9])-([0-9]|[1-5][0-9])))(\/([1-9]|[1-5][0-9]))?)\z/]
]

**Comment by bastelfreak** [comment]
Hi @repperille, thanks for reporting this. Are you able to provide a bugfix PR for this?

**Comment by jcbollinger** [comment]
This was a breaking change from v1.1.1, and it affects _all_ date and time fields, not just `hour` and `minute`.  Moreover, some versions of cron also accept ranges as list elements, skip counts on ranges, and / or skip counts on '*'. v1.2.0 accepts none of these.  My suggestion in fact would be to **revert** the introduction of data types for now, as it certainly should not have been introduced in its present form without bumping the module's major version.

I might nevertheless be prepared to work on a PR to provide more inclusive type definitions, but before I invest much effort into that I'd like to get some feedback about what actually should be done.

**Comment by jcbollinger** [comment]
Nevertheless, if you prefer to move ahead with more tightly constraining data types then I have worked up a PR which I will offer shortly.  Whether you choose to go forward in that direction or to revert, however, I urge you to do it soon, and to roll a new realease, for 1.2.0 produced breakage that people relying on semver had no reason to expect.
