### ISSUE TITLE
Special parameter is now set incorrectly with two @

### ISSUE THREAD

**Issue by dnlsng** [voxpupuli/puppet-cron#59]
Now that we have validation on the special parameter to cron::job, it is enforcing a value with an '@' symbol e.g. @reboot. However, the template already has the '@' symbol prepended to the special cron jobs. This means we get two @ symbols instead of one which is incorrect i believe.

We should either edit the cron::special type and remove the '@'s or edit the template and remove the @ from there.

**Comment by dnlsng** [comment]
I think we should leave the template alone as it is as that was there first and just update the type.

**Comment by amandamoffatt** [comment]
Hi, is there any indication of when this might be resolved? We rely on this functionality.

**Comment by alexjfisher** [comment]
@amandamoffatt Thanks for the nudge! :)
