### ISSUE TITLE
Implement CIS Benchmark requirements

### ISSUE THREAD

**Issue by ggeldenhuis** [voxpupuli/puppet-cron#65]
The CIS benchmarks specifies specific permissions on the default cron files. It would be usefull if this module could implement such functionality to allow you to manage it if you wanted in addition to managing cron files.

**Comment by bastelfreak** [comment]
Hi @ggeldenhuis, are you able to provide a PR for this?

**Comment by alexjfisher** [comment]
@ggeldenhuis Could you tell us in this ticket what those permissions are, or link to the docs?

**Comment by kenyon** [comment]
Closed by #75.
