### ISSUE TITLE
Open to merging back upstream?

### ISSUE THREAD

**Issue by torrancew** [voxpupuli/puppet-cron#9]
@roman-mueller I've been reviving my `cron` and `account` modules, and see that this is the current incarnation of a PR I neglected long ago. Would you have any interest in re-merging upstream?

**Comment by roman-mueller** [comment]
Sure, but it's not only a fork with one PR merged.  
I've refactored a lot, added some features and got a few pull requests here (hence the detachment of the fork).
Not sure how easy it will be to merge that back now.

**Comment by torrancew** [comment]
@roman-mueller I'll take a peek, and try to scope that out.

**Comment by nvtkaszpir** [comment]
Maybe move to voxpopuli https://voxpupuli.org/ ?
